### ISSUE TITLE
Price-level in homey app is not correct (?)

### ISSUE THREAD

**Issue by kimhegg** [tibber/com.tibber.athom#47]
<img src="https://user-images.githubusercontent.com/7045229/190120817-96f7ff05-6245-4acb-8811-d328583ec151.jpg" width="300" height="500">

<img src="https://user-images.githubusercontent.com/7045229/190120797-d27ba735-7cad-44f8-a94a-d206ef84e38e.jpg" width="300" height="500">

Or is price-level calculated based on some other mean? 
Anyway, i think the price-level in the homey-app should reflect current price-level as seen in the tibber-app.

**Comment by jstaro** [comment]
Thanks for the input!
We did release a version of the Homey app last year that did attempt to harmonize the price levels with the Tibber mobile app's price levels, but it was poorly communicated and hastily implemented, so it was (rightly) ill-received and we reverted back to the old price levels. The calculations (and the amount of price levels) are indeed different.

It's not off the table to revisit this in the future but we'd do some better groundwork before jumping into that.

**Comment by ianbednar** [comment]
The Tibber app in Homey has shown the same energy price the last 24 hours. In Tibber there has been many changes. I have tried restarting the app in Homey. This had no effect.

**Comment by jstaro** [comment]
@ianbednar The underlying API had a price cache issue on Saturday and Sunday which should now be fixed. Do you still experience problems?

**Comment by iver56** [comment]
@jstaro I noticed the issue for a few hours on monday too. Wouldn't it be more robust to do only _one_ request per day, where it loads energy prices for all 24 hours? Relying on network requests each hour throughout the day seems less robust to backend problems like the one you discovered. Also check if Homeys are programmed to run the hourly API requests at the same time - if so, it may produce a big peak in the traffic on your backend. Adding a random delay to such API requests can help, if it's not already in place.

One more wish: Cards like "Current price is one of today's highest x prices" should ideally raise an error when the client doesn't have up-to-date information available, instead of _trying to silently return an answer_ that is likely wrong (because it's based on old/wrong data). Implementing the error outcome correctly allows users to catch and handle it in advanced flows.

![bilde](https://user-images.githubusercontent.com/1470603/198048306-38d62f15-1c13-4646-a2fb-f73d73c2cea1.png)

**Comment by jstaro** [comment]
>  Wouldn't it be more robust to do only one request per day, where it loads energy prices for all 24 hours? 

That is what we are doing. With additional retry logic upon different types of failures, or if prices arrive late (they do not always arrive at a precise time).

> Also check if Homeys are programmed to run the hourly API requests at the same time - if so, it may produce a big peak in the traffic on your backend. Adding a random wait before such API requests can help, if it's not already in place.

Oh, we do that. All the thousands of Homeys hitting us at the same time would bring us to our knees, so that's a necessity.

Thanks for the suggestion regarding error conditions. This will now be much more important with Advanced Flows in place.
